### PR TITLE
[DO NOT MERGE YET] Add More Pixel Art Upscaling Algorithms

### PR DESCRIPTION
**Pull request by drummyfish**
I am trying to add more pixel art upscaling algorithms as discussed [here](https://github.com/ImageMagick/ImageMagick/issues/1143). This PR is work in progress, I am opening it early to get potential feedback as I am new to ImageMagick and may need some guidance.

Upscaling with pixel art Scale2x algorithm is already supported by IM via `-magnify` option, but only with scale2x algorithm. After this PR I'd like to have an option to specify one of the algorithms such as HQ2x, eagle, scale3x etc. I have also [created my own algorithm](https://github.com/mgba-emu/mgba/pull/737) for MGBA emulator and could add it.

The algorithm should be specified with `-define`, e.g.:

~~`convert -magnify -define "magnify:alg=eagle" in.png out.png`.~~

`convert in.png -define "magnify:method=eagle" -magnify out.png`.

Feel free to write me feedback here. I'll fix the code formatting before merging, I'm not used to this particular style.

EDITS/Notes:

- ~~Comparing pixels based on intensity, as currently implemented, may lead to bugs as two pixels can have the same intensity but different colors, in which case they should probably be considered different.~~ <-- addressed
- Make sure lines aren't longer than 80 chars.
- While some of the algorithms (XBR, ...) usually use pixel comparison with YUV specified error, I am currently comparing pixels for exact values only. The results are basically the same, but may be different for some cases (such as photos). Is this OK or should I stick to the more complicated YUV behavior? If so, the error value might possibly be specified with another -define.
- XBR seems to be a little different from the reference (rewritten from [here](https://github.com/carlosascari/2xBR-Filter/blob/master/xbr.js), reference [here](https://upload.wikimedia.org/wikipedia/commons/c/ce/Pixel-Art_Scaling_Comparison.png)).
- Behavior with indexed-color PNGs that have an alpha channel is buggy (happens also before my changes, IM exits with `Aborted`). `SetImageColorspace` to RGB fixes this but needs to make a copy of the source image.

implemented:

- eagle2x
- HQ2x
- XBR2x
- scale2x (EPX)
- EPBX2x
- eagle3x
- eagle3xb
- scale3x
- fish (my algorithm mentioned above)

### CODE REVIEW

**Comment by dlemstra** [comment]
@drummyfish Looks like a good start 👍  Could you make sure that your lines are not larger than 80 chars?

**Comment by drummyfish** [comment]
> Could you make sure that your lines are not longer than 80 chars?

I definitely will when I get to fixing the formatting part.

**Comment by drummyfish** [comment]
So I have a bunch of methods implemented now. I also tried to fix the formatting, though I probably missed some stuff. Here is what the results currently look like:

image

I'll need some more feedback and code review etc - I'm not really a C programmer so the code will probably need polishing. Also what should I do next? Should I update some documentation somewhere etc.? Can the helper functions stay where they are?

Thank you for all your help.

**Comment by hummeleBop** [comment]
Any news about this upcoming feature ?

**Comment by GithubSuckBigTime** [comment]
Hello, this is OP here. I've left GitHub, which is indicated on my profile, and have long lost track of this feature.

I'd be very glad if someone could finish this though. As far as I remember this was already working, and I've already used it in practice a few times, so there may even be no extra work required than to review and merge, but I don't guarantee this. Feel free to close this PR and create a new one, copy-paste the code or anything, I don't care about any credit or whatever, would just be shame if this was lost I guess.

**Comment by hummeleBop** [comment]
Thanks for your answer.
I can't handle that by myself but it would be amazing.

Too bad, good luck for your next projects :)

**Pull request merged**
