### PR TITLE
Remove files built by build process.

### PR DESCRIPTION
**Pull request by Danack**
This files get regenerated by ./configure and so I don't believe they should be under source control.

### CODE REVIEW

**Comment by dlemstra** [comment]
The files have been removed from our SVN repository.

**Comment by Danack** [comment]
Hi - it appears the file is still in git, but just as a zero-length file. https://github.com/ImageMagick/ImageMagick/blob/master/PerlMagick/Makefile.PL

**Comment by urban-warrior** [comment]
It is required for PerlMagick to build under Windows with Strawberry Perl.  Dirk, may be able to generate it with the Windows configure program-- until then Makefile.PL will remain as an empty file.

**Comment by dlemstra** [comment]
The Windows configure program has been modified and the file has been removed again.

**Pull request closed without merging**
