### PR TITLE
add libtiff and libde265 to the oss-fuzz build scripts

### PR DESCRIPTION
**Pull request by reaperhulk**
This will enable TIFF and HEIF fuzzing. We can add more libs (like freetype, etc) as we go.

refs https://github.com/google/oss-fuzz/pull/1263

### CODE REVIEW

**Comment by dlemstra** [comment]
I wonder if we should clone those libraries in our own scripts. Maybe a `clone.sh` script? And I would prefer to clone the copies that we have for the Windows build. We won't link against the latest development code then.

**Comment by reaperhulk** [comment]
The OSS-Fuzz project prefers the data to be cloned during container generation and generally wants development versions so that if issues are found in dependencies they can be fixed and those fixes will quickly propagate to the fuzzer.

**Comment by dlemstra** [comment]
I think it would be nice if we could avoid the PR in the oss-fuzz repo when we add another delegate. Can we not clone the dependencies in a script that is inside the ImageMagick repository?

And how will issues that happen in the other repository be managed? Do we need to contact the owners of the other repository to get this fixed? What would the procedure become?

**Comment by reaperhulk** [comment]
OSS-Fuzz PRs are typically merged extremely quickly, but we can ask if there's a specific reason for the dockerfile logic or if it's just convention.

We will be responsible for contacting upstreams if bugs are found in the dependencies.

**Pull request merged**
