### PR TITLE
(DO NOT MERGE) OpenRaster (.ora) decoder support

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have verified that there are no overlapping [pull-requests](https://github.com/ImageMagick/ImageMagick/pulls) open
- [ ] I have verified that I am following the existing coding patterns and practices as demonstrated in the repository (I did my best to emulate the code style, but I am unfamiliar with this repository)

### Description
The OpenRaster format (https://www.freedesktop.org/wiki/Specifications/OpenRaster/) is a format used in Krita and MyPaint. As such, it be useful to be able to read from said format to modify any Picture created in said app to, for instance:
- Convert it to a format better supported on the web
- Apply any of ImageMagick many operations to the Picture
- etc.

The OpenRaster format is a ZIP Archive following the format in https://www.freedesktop.org/wiki/Specifications/OpenRaster/Draft/FileLayout/. Of particular note, the archive contains "/mergedimage.png", which contain the final rendered image. Thus, to implement support, I read that file from the ZIP archive.

Fixes half of https://github.com/ImageMagick/ImageMagick/issues/1547, I need to research more about Krita file format before I can create the decoder of .kra

### Risks

Sadly, it doesn't appear any of the current dependencies have ZIP Archive support; the compression libraries I saw from a quick glance of the code only compress/decompress, not read from an archive. As such, I added libzip 1.0.0 as a dependency. 

### TODO

- Tests
- <del>Actually make it work; the code provided is just to 1. get it to build the additional decoder and 2. be a basic outline of how it should work. Currently, it doesn't recognize my decoder to be the decoder for .ora files, and it probably have some bugs since I am unfamiliar with this code base. Decided to open this PR early to get feedback.</del>

### CODE REVIEW

**Comment by Christopher-Chianelli** [comment]
Update: figured out why my decoder wasn't being detected; I set it format_type to implict, which meant it doesn't assume type from file name. Changing it to explicit fixes it. I know the image it extracts to the temp file is correct (I am able to view the image on my computer), but despite explicitly setting the image type to be PNG, I get
```
identify: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/562.
```
it might be because the temporary file I write to have no file extension?

**Comment by Christopher-Chianelli** [comment]
(Look like I don't have PNG image support; probably need to install libpng)

**Comment by Christopher-Chianelli** [comment]
Okay, got everything to work. It should now also degrade to not having ORA support if libzip is not installed.

**Comment by Christopher-Chianelli** [comment]
Future work: add support for extracting layers from the ORA image using https://www.freedesktop.org/wiki/Specifications/OpenRaster/Draft/LayersStack/ (note: ORA image may contain SVG, PNG and others, and you need to do transforms on them to get the mergedimage.png; extracting the mergedimage.png is less prone to errors than combining all the layers together, but doesn't allow extracting individual layers).

**Comment by urban-warrior** [comment]
Use /* */ in your comments.  Not all C compilers accept // as a comment (e.g. // #if defined(MAGICKCORE_LIBZIP_DELEGATE)).

In RegisterORAImage(), do not conditionally compile the entire block.  Instead, conditionally compile only the `entry->decoder...` statement.

Can you post a link to a few reference ORA image files?  We will need those for our image reference library.

**Comment by Christopher-Chianelli** [comment]
@urban-warrior Here are two sample images (Found in the MyPaint test suite): https://github.com/mypaint/mypaint/raw/master/tests/bigimage.ora https://github.com/mypaint/mypaint/raw/master/tests/smallimage.ora

**Comment by Christopher-Chianelli** [comment]
(I believe those images are licensed under GPL, so you may not want to include them directly in the repo. I can also create some OpenRaster images if that be of assistance).

**Comment by urban-warrior** [comment]
Exported an ORA image from gimp and could read it with your patch.  However, for your samples, we get:

```
convert bigimage.ora bigimage.png
convert: unable to open file 'bigimage.ora': No such file or directory @ error/ora.c/ReadORAImage/155.
convert: no images defined `bigimage.png' @ error/convert.c/ConvertImageCommand/3285.
```

**Comment by urban-warrior** [comment]
We won't include the sample ORA images in the ImageMagick repo.  Instead, we have an internal repo we use for offline unit testing of ImageMagick before a release.

**Comment by Christopher-Chianelli** [comment]
I know one of the samples is quite old, perhaps from before when `mergedimage.png` was mandatory (it was optional a long time ago, (before 0.0.2) but became mandatory when it became a more popular format to increase viewer software support). To support those old images, I would need to implement the layering support from reading stack.xml and layering all the images together.

**Comment by Christopher-Chianelli** [comment]
(can confirm it a file from before 0.0.2; no mergedimage.png in root upon unzipping)

**Pull request merged**
