### PR TITLE
Removed a seamingly useless write in color.cpp

### PR DESCRIPTION
**Pull request by mrbesen**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/ImageMagick/ImageMagick/pulls) open
- [x] I have verified that I am following the existing coding patterns and practices as demonstrated in the repository.

### Description
The write in line 264 seems to be overwritten by line 268 so i removed it.

### CODE REVIEW

**Comment by mrbesen** [comment]
Can you give me some explanation, what is wrong with my change, please?
Did i made a mistake and the write is not overwritten anyways?

**Comment by urban-warrior** [comment]
Pressed the wrong button.  We fixed the issue by manually installing the patch with a link back to this pull.

**Comment by ValZapod** [comment]
I think just pixel.alpha_trait on line 264 should be _pixel.alpha_trait

**Comment by dlemstra** [comment]
Can you clarify what you mean @ValZapod? We are now setting the `pixel.alpha_trait` on line `266`.

**Comment by ValZapod** [comment]
> now setting the `pixel`

I was talking about this 

https://github.com/mrbesen/ImageMagick/blob/5c6d97c3ecf2596039254ecaf5dc276cc4bf8e54/Magick%2B%2B/lib/Color.cpp#L432

**Comment by dlemstra** [comment]
That line looks fine to me?

**Comment by ValZapod** [comment]
> That line looks fine to me?

Well, it is very C++ that is for sure. If you sure 4 components will be recognized as RGBA vs CMYK depending on Adobe transfer field in the marker, then okay.

**Pull request closed without merging**
