### PR TITLE
Stop overwriting index.html with copy from root directory

### PR DESCRIPTION
**Pull request by cjmayo**
Breaks local navigation links, css and images

### CODE REVIEW

**Comment by mikayla-grace** [comment]
We're not seeing any problems with index.html.  We installed the latest ImageMagick and browsed it @ /usr/share/doc/ImageMagick-6/index.html.  The page rendered and navigation worked as expected.

**Comment by cjmayo** [comment]
Just showing the end of the comparison between the two index.html files:
```
ImageMagick $ diff -u index.html www/index.html
...
   <footer class="magick-footer">
-    <p><a href="https://legacy.imagemagick.org/www/support.html">Donate</a> •
-     <a href="https://legacy.imagemagick.org/www/sitemap.html">Sitemap</a> •
-    <a href="https://legacy.imagemagick.org/www/links.html">Related</a> •
-    <a href="https://legacy.imagemagick.org/www/security-policy.html">Security</a> •
-    <a href="https://legacy.imagemagick.org/www/architecture.html">Architecture</a>
+    <p><a href="support.html">Donate</a> •
+     <a href="sitemap.html">Sitemap</a> •
+    <a href="links.html">Related</a> •
+    <a href="security-policy.html">Security</a> •
+    <a href="architecture.html">Architecture</a>
 </p>
     <p><a href="index.html#">Back to top</a> •
     <a href="http://pgp.mit.edu:11371/pks/lookup?op=get&amp;search=0x89AB63D48277377A">Public Key</a> •
-    <a href="https://legacy.imagemagick.org/https://www.imagemagick.org/script/contact.php">Contact Us</a></p>
+    <a href="https://www.imagemagick.org/script/contact.php">Contact Us</a></p>
         <p><small>©  1999-2016 ImageMagick Studio LLC</small></p>
   </footer>
 </div><!-- /.container -->
 
   <script src="https://localhost/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
-  <script src="https://legacy.imagemagick.org/js/magick.html"></script>
+  <script src="../js/magick.html"></script>
 </div>
 </body>
 </html>
```

The links in the copy in the root directory are all absolute pointing to https://legacy.imagemagick.org, whereas the copy in the www subdirectory has relative links.

**Comment by mikayla-grace** [comment]
The solution is to fix the index.html file to have relative links.  We have a proper root index.html file for ImageMagick version 7.  We'll have a fix for ImageMagick version 6 in the next point release of ImageMagick.  Thanks for alerting us to this problem.

**Comment by cjmayo** [comment]
Thanks for investigating - even when the patch isn't great and I should have explained more clearly at the beginning.

**Pull request closed without merging**
