### PR TITLE
Fix wrong heic width and height when heic:preserve-orientation=true

### PR DESCRIPTION
**Pull request by liuzhe0223**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/ImageMagick/ImageMagick/pulls) open
- [x] I have verified that I am following the existing coding patterns and practices as demonstrated in the repository.

### Description

Fix bug introduced by #1436 
1. Photo https://www.dropbox.com/s/celi7ejhit9ybzb/test.heic?dl=0  rotation=270.
2. `magick convert -define heic:preserve-orientation=true test.heic test.jpeg`.
3.  The `test.jpeg` would be  corrupted,  because `heif_decode_image`  with `ignore_transformations=1` option  swapped width and height .

Sorry for this mistake.

### CODE REVIEW

**Comment by dlemstra** [comment]
I don't think this is the proper solution. Will need some time to think about a correct solution.

**Comment by liuzhe0223** [comment]
👌

**Comment by liuzhe0223** [comment]
Yes,  https://github.com/ImageMagick/ImageMagick/commit/74c8d1f57fd76826a4b38a0e3bb5c71166cad809 resolved this issue, have tried like this but not sure about `SetImageExtent ` when use wrong width and height.

I will close this pull-request.

**Comment by dlemstra** [comment]
@liuzhe0223 Thanks for making me realize that I was missing a call to `SetImageExtent`. Fixed that in another patch: https://github.com/ImageMagick/ImageMagick/commit/8c69a644b1a32dd032541d123d232003f05887f8.

**Comment by liuzhe0223** [comment]
😃

**Pull request closed without merging**
