### PR TITLE
Fix multiple DDS output issues [port to ImageMagick-6]

### PR DESCRIPTION
**Pull request by Hrnchamd**
Port of #137 as requested.

### CODE REVIEW

**Comment by dlemstra** [comment]
Your patches have been merged. Thanks for your contribution! :+1:

**Comment by svengineer99** [comment]
Is / when should this be available for beta / official release download?

**Comment by dlemstra** [comment]
It should be in the beta now and will be released this Saturday.

**Comment by svengineer99** [comment]
I tried http://www.imagemagick.org/download/beta/ImageMagick-6.9.3-9~beta20160428-Q16-x64-dll. exe but I still get blocky compression=dtx5 and unreadable by paint.net compression=none outputs. 
Win8\Control Panel\Programs\Programs and Features\ shows program name "ImageMagick 6.9.3-9 Q16 (32-bit) (2016-04-24) that date would be before this patch was merged.  Should I look for the beta somewhere else?

Many thanks.

**Comment by dlemstra** [comment]
Our Windows beta's are only updated weekly. And the last release was before this patch got merged. It will be available in the release that will be published later today.

**Comment by svengineer99** [comment]
Thanks.  I just left my feedback on the OP https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=27169&p=132698#p132698

**Pull request closed without merging**
