### PR TITLE
Backport complex text layout from master

### PR DESCRIPTION
**Pull request by ShamsaHamed**

### CODE REVIEW

**Comment by mikayla-grace** [comment]
We applied your patch to the ImageMagick-6 branch.  Thanks.

**Comment by mikayla-grace** [comment]
When you get a chance, can you verify that complex text layout is working properly in the latest ImageMagick 6 and 7 releases.  Thanks.

**Comment by Fahad-Alsaidi** [comment]
I have tested ImageMagick 7 and it works fine. However, when I tried to complie ImageMagick6 I got this error:
```
make[1]: Entering directory `/home/ita/learn/ImageMagick'
  CC       magick/magick_libMagickCore_6_Q16_la-annotate.lo
magick/annotate.c: In function ‘ComplexTextLayout’:
magick/annotate.c:1038:7: error: unknown type name ‘TokenInfo’
       TokenInfo
       ^
magick/annotate.c:1042:7: warning: implicit declaration of function ‘AcquireTokenInfo’ [-Wimplicit-function-declaration]
       token_info=AcquireTokenInfo();
       ^
magick/annotate.c:1042:17: warning: assignment makes pointer from integer without a cast [enabled by default]
       token_info=AcquireTokenInfo();
                 ^
magick/annotate.c:1044:7: warning: implicit declaration of function ‘Tokenizer’ [-Wimplicit-function-declaration]
       status_token=Tokenizer(token_info,0,token,50,features,"",",","",'\0',
       ^
magick/annotate.c:1052:7: warning: implicit declaration of function ‘DestroyTokenInfo’ [-Wimplicit-function-declaration]
       token_info=DestroyTokenInfo(token_info);
       ^
magick/annotate.c:1052:17: warning: assignment makes pointer from integer without a cast [enabled by default]
       token_info=DestroyTokenInfo(token_info);
                 ^
make[1]: *** [magick/magick_libMagickCore_6_Q16_la-annotate.lo] Error 1
make[1]: Leaving directory `/home/ita/learn/ImageMagick'
make: *** [all] Error 2

```

I have libraqm installed and it is showed in DELEGATES list in ImageMigick 7 but not in ImageMgick 6, something is missing I think in configure

**Comment by mikayla-grace** [comment]
When you get a chance, try again.  We added a patch to magick/annotate.c and configure.ac.  Thanks.

**Comment by Fahad-Alsaidi** [comment]
@mikayla-grace It now works fine for me. I am waiting @ShamsaHamed  to confirm from her side.

**Comment by ShamsaHamed** [comment]
@Fahad-Alsaidi I am now testing them, but did you test font-features? I am trying to test them, I don't find how to use the option.

**Comment by Fahad-Alsaidi** [comment]
I think now ImageMagick doesn't support any font-features. The good news that we now use Harfbuzz which supports them and libraqm supports also them.
What we need now is a way to pass font features to libraqm.  I tried to use "-features" option but doesn't work. 
@mikayla-grace could you please help us here?

**Comment by ShamsaHamed** [comment]
@Fahad-Alsaidi  I found out in their commits that they change the option from '-font-features' to use '-define type:features', but still I can't use it. 
@mikayla-grace could you please explain to me how to use it?

**Comment by mikayla-grace** [comment]
Did you try -define type:features=<features> or -set type:features <features>?  If that fails, send us a set of features and we'll test it and see if we can reproduce the problem.

**Comment by ShamsaHamed** [comment]
Yes I have tried it. I print the value of feature but it show a null value. 
You can try ligature feature (-liga). 
I am using it like that: 
utilities/magick -size 1000x500 xc:lightblue -font /home/shamsa/DejaVuSans.ttf -pointsize 72 -fill blue -define type:features='-liga'  -draw "text 25,65 'filling'" text_draw.gif

**Comment by saoirse-ronan** [comment]
Try this command:

    utilities/magick -size 1000x500 xc:lightblue -font /home/shamsa/DejaVuSans.ttf -pointsize 72 -fill blue -set type:features '-liga' -draw "text 25,65 'filling'" text_draw.gif

**Comment by Fahad-Alsaidi** [comment]
This works for me:
````
magick -size 1050x510 xc:lightblue -font /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf -pointsize 72 -fill blue -set type:features 'liga' -draw "text 26,65 'fi fl ff fb ffb ffh ffi fj ffj fk ffk fl '" text_draw1.gif
````

**Comment by ShamsaHamed** [comment]
It's work fine with me. 
ImageMagick-6 is also fine.

**Comment by dlemstra** [comment]
Thanks for your contribution to ImageMagick :+1:. We will close this pull request now.

**Comment by ShamsaHamed** [comment]
Thanks a lot for your interaction with us. I am so happy that you accept my patch.

**Pull request closed without merging**
