### PR TITLE
fix multiple memory leak in ReadYUVImage

### PR DESCRIPTION
**Pull request by jgj212**
We found that there is multiple memory leak vulnerability in ReadYUVImage  because no memory free on exception condition. And we create patch here.

Credit: ADLab of Venustech

### CODE REVIEW

**Comment by dlemstra** [comment]
Thanks for helping us 👍. It seems that your changes now have conflicts. Can you rebase your changes to resolve this? And could you make sure that you are using the correct indentation? Might be incorrect because you are using tabs instead of spaces but I cannot see that now. We use 2 spaces for indentation.

**Comment by dlemstra** [comment]
And it looks like you also included your `ycbcr.c` fixes in this pull requests again. But with different indentation.

**Comment by jgj212** [comment]
@dlemstra  i will resolve conflicts, thank you

**Comment by jgj212** [comment]
I create a pull request, so closed this

**Pull request closed without merging**
