### PR TITLE
remove exec perm on source files

### PR DESCRIPTION
**Pull request by remicollet**
This create check failure on downstream packages (rpmlint)

### CODE REVIEW

**Comment by dlemstra** [comment]
Could you add another pull request for the master branch if we also have this issue there?

**Comment by remicollet** [comment]
See pr #86

**Comment by dlemstra** [comment]
Thanks for the quick response and patch :+1:

**Comment by dlemstra** [comment]
I cherry picked this one: https://github.com/ImageMagick/ImageMagick/commit/9e84b1cafecac89f8dc0c673b05ca5b532a710ea

**Pull request closed without merging**
