### PR TITLE
resolve #5241

### PR DESCRIPTION
**Pull request by unclesamwk**
### Prerequisites

- [ ] I have written a descriptive pull-request which add avif(rw)/heic(r) support

### CODE REVIEW

**Comment by dlemstra** [comment]
Why are you building this from source?

**Comment by dlemstra** [comment]
I think we should install packages instead of building them. Maybe we could change the container image to a more recent version of Ubuntu to get a more recent version?

**Comment by unclesamwk** [comment]
When i use ubuntu 20.04 or 22.04 linuxdeployqt doesn't work.

```
| linuxdeployqt  (commit d6ac06c), build 19 built on 2022-07-04 19:17:26 UTC
| ERROR: The host system is too new.
| Please run on a system with a glibc version no newer than what comes with the oldest
| currently still-supported mainstream distribution (Ubuntu Bionic), which is glibc 2.27.
| This is so that the resulting bundle will work on most still-supported Linux distributions.
| For more information, please see
| https://github.com/probonopd/linuxdeployqt/issues/340
```
https://github.com/probonopd/linuxdeployqt/issues/340
https://github.com/probonopd/linuxdeployqt/issues/536

**Comment by unclesamwk** [comment]
I have now split the compile and packing appimage into 2 different jobs. Unfortunately, I can not test this locally with act and the articats reasonably. Anyone else?

**Comment by dlemstra** [comment]
I did some reading this morning and the advice is to build on an older version of Ubuntu to make it work on older versions of Ubuntu. I am wondering if we could do what is mentioned in "Recommended alternative to pinning" described here: https://help.ubuntu.com/community/PinningHowto. This might make it possible to use a more recent version of libheif. And if that doesn't work I think we should install and use the older version instead for now. And "upgrade" to 20.04 once app-image uses a more recent version.

**Comment by unclesamwk** [comment]
I have tried pinning, but this requires all dependencies to be resolved and handled differently by pinning. I think that is unnecessary more effort. I personally don't understand where the problem is now. If an appimage file is successfully built, and everything works as expected, then you would have an upgrade from IM to 22.04 ready to go. Whether the build of the appimage is now done with 18.04 or later in higher versions has, does little to the matter.

**Comment by Sondro** [comment]
> I have tried pinning, but this requires all dependencies to be resolved and handled differently by pinning. I think that is unnecessary more effort. 

Unsure if you noticed, but under the page [dlemstra](https://github.com/dlemstra) referenced under 'Recommended **alternative to pinning**
' it mentions an alternative because pinning breaks & fails using `apt-get build-dep package` & `apt-get -b source -t package`.

Anyways, if this is going to take a while it would be nice to have animated AVIF support -- which would also cover #2788: https://github.com/ImageMagick/ImageMagick/issues/2788#issuecomment-727815710

**Comment by unclesamwk** [comment]
In ubuntu 18.04 the "initrip" doesn't really work either:
```
Err:6 http://archive.ubuntu.com/ubuntu intrepid Release
  404 Not Found [IP: 185.125.190.36 80]
```
It doesn't make sense to install on a not up to date ubuntu release.

**Comment by btimbermont** [comment]
@Sondro Could you please check the other PR that adds HEIC support to the app image?
It keeps using the old Ubuntu version as recommended for bnuilding app images, and  I have tested the github workflow and it produces a fully functional appimage with HEIC support.

The PR is this one:  https://github.com/ImageMagick/ImageMagick/pull/6098

**Comment by dlemstra** [comment]
Closing this now because #6098 added support for this.

**Pull request closed without merging**
