### PR TITLE
fix multiple memory leak in ReadYUVImage

### PR DESCRIPTION
**Pull request by jgj212**
We found that there is multiple memory leak vulnerability in ReadYUVImage because no memory free on exception condition. And we create patch here.

Credit: ADLab of Venustech

### CODE REVIEW

**Comment by jgj212** [comment]
I resolved the conflicts...

**Comment by dlemstra** [comment]
I am still seeing conflicts and changes in parts where your original pull request did not make any changes, see: https://github.com/ImageMagick/ImageMagick/pull/755/files. Not sure what is happening on your side. And instead of opening an new issue you could do a 'force push' of your branch to overwrite your changes.

**Comment by jgj212** [comment]
@dlemstra oh, my god

**Comment by jgj212** [comment]
close this to create a new pull request

**Comment by dlemstra** [comment]
Instead of opening an new issue you could do a 'force push' of your branch to overwrite your changes.

**Pull request closed without merging**
