### PR TITLE
Add "exact" option for WebP encoder

### PR DESCRIPTION
**Pull request by tomplus**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/ImageMagick/ImageMagick/pulls) open
- [x] I have verified that I am following the existing coding patterns and practices as demonstrated in the repository.

### Description

The official WebP encoder has an option named `exact` to disable some optimization (https://developers.google.com/speed/webp/docs/cwebp#additional_options). In this PR I'd like to add this to option to the ImageMagic.

Thanks!

### CODE REVIEW

**Comment by dlemstra** [comment]
Thanks for your contribution. When was this option introduced? It might need to be in one of the blocks that check for a specific version.

And thanks for making the documentation changes but they need to be done here instead: https://github.com/ImageMagick/Website. Would you be willing to open up a PR after we get this merged?

**Comment by dlemstra** [comment]
It looks like we need to move it in the same block as the `near_lossless` option.

**Comment by andrius4669** [comment]
0.5.0: https://chromium.googlesource.com/webm/libwebp/+/refs/heads/0.5.0/src/webp/encode.h#139 (didn't find that in earlier tags)

**Comment by tomplus** [comment]
I've found it here: https://chromium.googlesource.com/webm/libwebp/+/1f9be97c22d991816cd72a9d83569d15dcf75965^!/ - version 0x0209.

**Comment by tomplus** [comment]
Sure, I'll update Website repository. Should I rollback changes in www/webp.html?

**Comment by dlemstra** [comment]
We will sync that another time so yes please revert the documentation changes here.

**Comment by tomplus** [comment]
Thanks for merging it :+1:

**Comment by dlemstra** [comment]
Thanks for contributing 😁

**Pull request merged**
