### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by jgj212**
fix memory leak in tim.c
fix memory leak in sixel.c
fix memory leak in palm.c
fix memory leak in pes.c
fix memory leak in pict.c
fix memory leak in png.c
fix memory leak in miff.c
fix memory leak in meta.c
fix memory leak in map.c
fix memory leak in hrz.c
fix memory leak in gif.c
fix memory leak in flif.c
fix memory leak in dps.c
fix memory leak in cut.c

### CODE REVIEW

**Comment by dlemstra** [comment]
@jgj212 With `git push --force` you can overwrite your changes and then you won't have to open a new pull request when you make changes .

**Comment by jgj212** [comment]
@dlemstra can you send me your email, i have some question. My email is jgj212@gmail.com

**Comment by dlemstra** [comment]
And can you also make sure we release tim_data here: https://github.com/ImageMagick/ImageMagick/blob/master/coders/tim.c#L386

I will e-mail you when I get home tonight. My timezone is GMT+1 so you might be asleep then 😄

**Comment by dlemstra** [comment]
@jgj212 Feel free to add that to your changes.

**Comment by jgj212** [comment]
@dlemstra  i fixed another bug, can i commit it to my fork? If i commit it,  this pull request will be ok or not?

**Comment by jgj212** [comment]
@dlemstra my skype id is jgj212@gmail.com

**Comment by dlemstra** [comment]
I hope you are aware that you are sharing your email publicly here. You can edit your message and remove your email and skype id if you want. I have copied it.

**Comment by dlemstra** [comment]
Thanks for contributing 👍 . I just did a rebase in your repository to resolve some merging issues. You might want to do a new fork if you want to send us more pull requests.

**Pull request merged**
